# .pre-commit-hooks.yaml

repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'  # Use the latest stable version of mypy or specify your preferred version
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/psf/black
    rev: '23.1.0'  # Use the latest stable version of black or specify your preferred version
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # Use the latest stable version of flake8 or specify your preferred version
    hooks:
      - id: flake8
        args: [--max-line-length=88]
